name: "Hello world"
description: "My first real add-on!"
version: "1.2.0"
slug: "hello_world"
init: false
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8001/tcp: 8001
